---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_uninstalled_packages: []
homebrew_installed_packages:
  - asdf
  - coreutils
  - earthly
  - findutils
  - gnupg
  - gnu-sed
  - gnu-tar
  - gnu-indent
  - gnu-which
  - jq
  - starship
  - tcld
  - tmux
  - tree
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - jorgelbg/tap
  - temporalio/brew

homebrew_cask_appdir: /Applications
homebrew_cask_uninstalled_apps: []
homebrew_cask_apps:
  - karabiner-elements
  - via
  - logitune
  - logi-options-plus
  - battery
  - stats
  - secretive
  - font-meslo-lg-nerd-font
  - warp
  - aerial
  - brave-browser
  - google-chrome
  - firefox
  - discord
  - viber
  - vlc
  - zoom
  - steam
  - imageoptim
  - screen-studio
  - typora
  - obsidian
  - docker
  - android-studio
  - sublime-text
  - visual-studio-code
  - gitkraken
  - hyper
  - postman
  - figma
  - notion

# See `geerlingguy.mas` role documentation for usage instructions.
mas_uninstalled_apps: []
mas_installed_apps:
  - { id: 408981434, name: "iMovie" }
  - { id: 409183694, name: "Keynote" }
  - { id: 409201541, name: "Pages" }
  - { id: 409203825, name: "Numbers" }
  - { id: 682658836, name: "GarageBand" }
  - { id: 497799835, name: "Xcode" }
  - { id: 640199958, name: "Apple Developer" }
  - { id: 899247664, name: "TestFlight" }
  - { id: 1607635845, name: "Velja" }
  - { id: 1604176982, name: "One Thing"}
  - { id: 1263070803, name: "Lungo" }
  - { id: 1632827132, name: "Camera Preview" }
  - { id: 1294126402, name: "HEIC Converter" }
  - { id: 1575588022, name: "MenubarX" }
  - { id: 457622435, name: "Yoink - Better Drag and Drop" }
  - { id: 430798174, name: "HazeOver • Distraction Dimmer™" }
  - { id: 1451177988, name: "Petrify" }
  - { id: 1402042596, name: "AdBlock for Safari" }
  - { id: 1352778147, name:  "Bitwarden" }
  - { id: 1471867429, name: "OTP Auth" }
  - { id: 1480068668, name:  "Messenger" }
  - { id: 1147396723, name: "WhatsApp Desktop" }
  - { id: 803453959, name: "Slack for Desktop" }
mas_upgrade_all_apps: false
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"
