---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_uninstalled_packages: []
homebrew_installed_packages:
  # - ansible # Installed via Pip.
  # - autoconf
  # - bash-completion
  # - doxygen
  # - gettext
  # - gifsicle
  # - git
  # - github/gh/gh
  # - go
  # - gpg
  # - iperf
  # - libevent
  # - sqlite
  # - mcrypt
  # - nmap
  # - node
  # - nvm
  # - php
  # - ssh-copy-id
  # - cowsay
  # - readline
  # - openssl
  # - pv
  # - wrk
  # - zsh-history-substring-search
  - asdf
  - coreutils
  - findutils
  - gnupg
  - gnu-sed
  - gnu-tar
  - gnu-indent
  - gnu-which
  - httpie
  - jq
  - starship
  - tmux
  - tree
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - jorgelbg/tap

homebrew_cask_appdir: /Applications
homebrew_cask_uninstalled_apps: []
homebrew_cask_apps:
  # - chromedriver
  # - docker
  # - dropbox
  # - handbrake
  # - licecap
  # - sequel-ace
  # - slack
  # - sublime-text
  # - transmit
  - karabiner-elements
  - via
  - logi-options-plus
  - battery
  - stats
  - secretive
  - aerial
  - brave-browser
  - google-chrome
  - firefox
  - discord
  - viber
  - vlc
  - zoom
  - steam
  - battle-net
  - imageoptim
  - screen-studio
  - typora
  - obsidian
  - android-studio
  - sublime-text
  - visual-studio-code
  - gitkraken
  - hyper
  - postman
  - figma
  - notion

# See `geerlingguy.mas` role documentation for usage instructions.
mas_uninstalled_apps: []
mas_installed_apps:
  - { id: 408981434, name: "iMovie" }
  - { id: 409183694, name: "Keynote" }
  - { id: 409201541, name: "Pages" }
  - { id: 409203825, name: "Numbers" }
  - { id: 682658836, name: "GarageBand" }
  - { id: 497799835, name: "Xcode" }
  - { id: 640199958, name: "Apple Developer" }
  - { id: 899247664, name: "TestFlight" }
  - { id: 1607635845, name: "Velja" }
  - { id: 1604176982, name: "One Thing"}
  - { id: 1263070803, name: "Lungo" }
  - { id: 1632827132, name: "Camera Preview" }
  - { id: 1294126402, name: "HEIC Converter" }
  - { id: 1575588022, name: "MenubarX" }
  - { id: 457622435, name: "Yoink - Better Drag and Drop" }
  - { id: 430798174, name: "HazeOver • Distraction Dimmer™" }
  - { id: 1451177988, name: "Petrify" }
  - { id: 1402042596, name: "AdBlock for Safari" }
  - { id: 1352778147, name:  "Bitwarden" }
  - { id: 1471867429, name: "OTP Auth" }
  - { id: 1480068668, name:  "Messenger" }
  - { id: 1147396723, name: "WhatsApp Desktop" }
  - { id: 803453959, name: "Slack for Desktop" }
mas_upgrade_all_apps: false
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
