#!/bin/sh

PATH=~/Library/Python/3.9/bin:$PATH

# install requirements
ansible-galaxy install -r requirements.yml

# run ansible playbook
ansible-playbook main.yml --ask-become-pass -e 'ansible_python_interpreter=/usr/bin/python3'
